# Generated by Django 5.2.1 on 2025-05-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baosa', '0002_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baosa.member'),
        ),
    ]
